### ISSUE TITLE
Tokio for $OTHER_LANGUAGE Developers

### ISSUE THREAD

**Issue by rylev** [tokio-rs/doc-push#17]
There are other "documentation" that could be helpful, but may be best left to the community. It could be nice to encourage others to write about certain topics and link to them. 

For example: Tokio for $OTHER_LANGUAGE Developers.

**Comment by carllerche** [comment]
Tokio for $OTHER_LANGUAGE developers seems like a good set of guides to include on the website. I'm not sure what the best place to slot that in would be though.

**Comment by rylev** [comment]
I'll change the name of this issue to track such guides.
