### ISSUE TITLE
Examples of blocking calls

### ISSUE THREAD

**Issue by kadfak** [tokio-rs/doc-push#49]
I'm generally quite confused about what could be a blocking call and if I should do anything with the concerned call. I recently watched @jonhoo's open-source contributions [stream](https://www.youtube.com/watch?v=8UzLuMiGs9s) where he pointed out many cases where the library authors are using blocking calls and whatnot on tokio threads, etc. His solution most of the time was to use [tokio_threadpool::blocking](https://tokio-rs.github.io/tokio/tokio_threadpool/fn.blocking.html).

The idea here is to gather a set of real-world examples of blocking behavior to let even people who don't have much async experience to more easily understand what blocking *really* means and what to do about it.

I think it's important because more and more (web) libraries are using tokio. Even if some people don't use tokio directly, they must really understand the nature of async to get the most out of the benefits tokio provides.

Some examples that confuse me (from a web server POV):
- Executing database queries. Since the driver is communicating with the database and it's waiting for a response, does the tokio thread block? What if the DB driver uses a threadpool that is external to tokio, do I have to do anything differently when executing the query in a web library's request handler?
- Password hashing. It's a CPU-bound action. From @jonhoo's stream I saw that the [argounatica](https://github.com/bcmyers/argonautica/tree/master/argonautica-rs) library itself uses a threadpool, what should I do when hashing a password in this case? When a password hashing library doesn't use an internal threadpool, should I be the one now that uses `tokio_threadpool::blocking` like @jonhoo did in his stream?
- File system access. There is an issue about this topic: #21.
- HTTP request from within a tokio thread. Let's say we are using Hyper's HTTP client. In this case we have a library that returns `Future`s, so we can just return a `Future` ourselves and just chain it with `and_then`?
- Validating a JSON schema. This involves deserializing a JSON string into Rust objects and then matching the user provided JSON to a predefined schema. Does this play well when run on a tokio thread? What's the deciding factor of when something should be offloaded to an external cpupool?

The theme seems to repeat itself in my case: I'm not sure if I should do something about certain calls because of feeling clueless about these topics, lacking knowledge and not knowing where to look to solve such basic? issues.

Does that make sense?

**Comment by kadfak** [comment]
There's also #15

**Comment by carllerche** [comment]
Do you think this can be merged with #15 then?

**Comment by kadfak** [comment]
Yes, I think this can be tracked in #15.

**Comment by carllerche** [comment]
Thanks. Closing in favor of #15.
