### ISSUE TITLE
What is Tokio Overview

### ISSUE THREAD

**Issue by AndyGauge** [tokio-rs/doc-push#68]
I was left wondering how Tokio fits in with the rust asynchronous ecosystem.  I think a blurb about Tokio being a high level abstraction over lower level implementations will let people know that Tokio is probably the right tool to use.  

Also the link at the bottom is broken. (to examples)

**Comment by rawrmonstar** [comment]
Sorry to butt in, but I think it would be nice to make a clear distinction about what tokio is versus what futures are. I don't know if it's really the job of tokio to do that kind of education but, as a beginner, learning tokio is the first time I've encountered futures in Rust so clearly defining tokio's relationship to/distinction from futures would be really helpful to me.

**Comment by AndyGauge** [comment]
@rawrmonstar I agree that the Tokio guides should do this, and the link on the overview is where I believe that should happen.  https://tokio.rs/docs/getting-started/futures/

**Comment by carllerche** [comment]
Would someone mind opening a PR against the outline to include this item?
