### ISSUE TITLE
Which branch of 'tokio-rs/website' {should get PRs, is the current reference}?

### ISSUE THREAD

**Issue by barskern** [tokio-rs/doc-push#74]
> Tweak an existing guide
> Requires Experience: Beginner
> The guides are part of the website repository. If you see a way to tweak an existing guide to improve it, please open a PR.

There is many branches which seem to be fit for this purpose (e.g `master`, `docs-push`, `docs-blitz`). 

- Which branch is prefered to get PRs regarding the doc-push effort? 
- Which branch should be thought of as having the current updated guides (e.g the 'hello_world' guide in the `docs-blitz` branch is quite different from the one online)?

**Comment by carllerche** [comment]
@barskern everything should be against master :) We are doing it live!

That said, I should look at cleaning up branches.

**Comment by barskern** [comment]
That cleanup was much needed 😊 

Are the changes to the `doc-blitz` branch temporary or in-progress changes? E.g the `hello_world` example in this branch is quite different from the master branch. If eventually the `doc-blitz` branch will be merged into master a lot of the feedback regarding the current example would be slightly misplaced. Hence if that is the purpose, perhaps this branch should be merged so that people using the website will see the newest suggestions to the tutorials (despite them being work in progress)?

**Comment by carllerche** [comment]
I don't know why the doc-blitz branch was still around. I deleted it and rebased your PR.

I want to try to keep changes merged to master (and to the live site) as soon as possible, even if it creates some blank pages. These pages can be used to let people know about the doc push effort.

**Comment by carllerche** [comment]
Ok, I have deleted all non master branches. Closing this now 👍
